import Head from 'next/head'
import { FaWhatsapp, FaTelegramPlane, FaInstagram, FaUserFriends } from 'react-icons/fa'
export default function Home() {
  return (
    <>
      <Head>
        <title>FUN WAGERZ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="header-top-area s-header-top-area d-none d-lg-block">
          <div className="container-fluid s-container-full-padding">
            <div className="row align-items-center">
              <div className="col-lg-6 d-none d-lg-block">
                <div className="header-top-offer">
                  <a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site">
                    <p>Get Trusted Online ID Here </p> </a>
                </div>
              </div>
              <div className="col-lg-6">
                <div className="header-top-right">
                  <div className="header-social">
                    <ul>
                      <ul className="sm-megamenu-hover sm_megamenu_menu sm_megamenu_menu_black">
                        <li><a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site"
                          target="/">Home</a> </li>
                        <li><a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site"
                          target="_blank">Contact Us</a></li>
                        <li><a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site"
                          target="_blank">Privacy Policy</a></li>
                      </ul>

                    </ul>
                  </div>
                  <div className="header-top-action">

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
      <main>
        <div className="home-senction">
          {/* <!-- <h2>Carousel Example</h2> --> */}
          <section className="slider-area slider-bg">
            <div className="home-page">
              <div className="container slider-bg-one">
                <div className="row justify-content-center">
                  <div className="col-xl-9">
                    <div className="slider-content text-center">
                      <h6 className="wow fadeInDown" data-wow-delay=".2s">
                        <span className="text-light">Fun Wagerz</span>
                        <br />
                        Get your trusted Online ID
                      </h6><br />
                      <div className="d-flex justify-content-center text-center">
                        <button className="wow btn"> Whatsapp Now</button>
                      </div>
                      <br />
                      <h2 className="tlt fix" data-in-effect="fadeInLeft">
                        <span style={{ visibility: "hidden" }} aria-label="Trusted Online Cricket id provider ">
                          <span className="word1" aria-hidden="true" aria-label="Trusted" style={{ display: 'inline-block', transform: 'translate3d(0px, 0px, 0px)' }}>
                            <span className="char1" aria-hidden="true" style={{ display: 'inline-block', visibility: 'visible', }}> 100% Genuine</span>
                          </span>
                        </span>
                        <span className="word2" aria-hidden="true" aria-label="Online" style={{ display: 'inline-block', transform: 'translate3d(0px, 0px, 0px)' }}>
                          <span className="char1" aria-hidden="true"
                            style={{ display: 'inline-block', visibility: 'visible', }}>
                            and Trusted Online Cricket ID provider
                          </span>
                        </span>
                        <ul className="texts" style={{ display: "none" }}>
                          <li className="current">Trusted Online Cricket id provider</li>
                        </ul>
                      </h2>
                      <p className="wow fadeInUp" data-wow-delay="2s">500000+
                        Players playing on Funwagerz, the leading promoter of online sports fantasy
                        games in India. Get your ID in under 2 minutes!
                      </p>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <a target="_blank" href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site"
          className="enq-side-btn-icone"><i><FaWhatsapp /></i></a>
        {/* <!-- breadcrumb-area --> */}
        {/* <!-- game-single-area --> */}
        <section className="game-single-area pt-120 pb-120">
          <div className="container">
            <div className="row">
              <div className="col-12">
                <div className="game-single-content">
                  <div className="upcoming-game-head">
                    <div className="uc-game-head-title">
                      <h4>
                        WELCOME TO THE <span> FUN WAGERZ FAMILY -THE OLDEST FANTASYSPORTS PROVIDER
                          ININDIA</span>
                      </h4>
                    </div>
                    <a target="_blank" href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site" >
                      <div className="uc-game-price">
                        <h5>Get Your ID RIGHT NOW with 100 Welcome Bonus.</h5>
                      </div>
                    </a>
                  </div>
                  <p>
                    Contact Fun Wagerz if you have any questions, emergencies, feedback, or complaints. With
                    our WhatsApp services, we are available 24 hours a day, 7 days a week.
                  </p>
                  <p>
                    Welcome to Fun Wagerz, where we provide a truly unique fantasy sports experience.
                    Furthermore, we have a global network and offer the best industry experience with a
                    single click.
                  </p>
                  <p>
                    Fun Wagerz promotes fantasy sports responsibly. We provide a wide range of fantasy
                    sports
                    games. We have assisted over 50000 participants in locating the greatest fantasy sports
                    sites online.
                  </p>
                  <p>
                    Our company operates in a very open and honest manner. Get Your Demo ID Right Now!
                  </p>

                  <div className="game-single-title mt-60 mb-30">
                    <h4>Why Choose Us</h4>
                  </div>
                  <div className="game-single-info mb-65">
                    <ul>
                      <li>24*7 Support</li>
                      <li>Instant Reply</li>
                      <li>Most Trusted & Secure Platform</li>
                      <li>5 lac+ Active User</li>
                      <li>10+ sites/exchange</li>
                      <li>Present in UAE & abroad</li>
                      <li>NO CAP on Maximum withdraw in a day</li>
                      <li>Upto 15% Deposit Bonus Available</li>
                    </ul>
                  </div>
                  <div className="footer-widget">
                    <div className="fw-title my-5">
                      <h5>Follow us</h5>
                    </div>
                    <div className="footer-social">
                      <ul>
                        <li><a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site" target="_blank">
                          <i><FaInstagram /></i>
                        </a></li>
                        <li><a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site" target="_blank">
                          <i><FaTelegramPlane /></i>
                        </a></li>
                        <li><a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site" target="_blank">
                          <i><FaWhatsapp /></i>
                        </a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div className="container my-5">
          <h2 className="text-center pt-5 text-dark my-5 pb-4">Multiple Payment Options</h2>
          <div className="row">
            <div className="mt-4 col col-xl-3 col-lg-3 col-md-6 col-sm-6 col-xm-12 col-12">
              <button className="innerCard">
                <img src="/paytm.png" alt="khelo Online" />
              </button>
            </div>
            <div className="mt-4 col col-xl-3 col-lg-3 col-md-6 col-sm-6 col-xm-12 col-12">
              <button className="innerCard">
                <img src="/Maestro.png" alt="khelo Online" />
              </button>
            </div>
            <div className="mt-4 col col-xl-3 col-lg-3 col-md-6 col-sm-6 col-xm-12 col-12">
              <button className="innerCard">
                <img src="/RuPay.png" alt="khelo Online" />
              </button>
            </div>
            <div className="mt-4 col col-xl-3 col-lg-3 col-md-6 col-sm-6 col-xm-12 col-12">
              <button className="innerCard">
                <img src="/visa.png" alt="khelo Online" />
              </button>
            </div>
          </div>
          <div className="paybtn">
            <a className="" href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site" target="_blank">
              <FaWhatsapp /> <span>WhatsApp Now</span></a>
            <a className="" href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site" target="_blank">
              <FaUserFriends /><span>Get Your Cricket ID</span></a>
          </div>
        </div>
      </main>
      {/* <!-- footer-area --> */}
      <footer>
        <div className="footer-top footer-bg s-footer-bg">
          <div className="container">
            <ul className="sm-megamenu-hover sm_megamenu_menu sm_megamenu_menu_black sdfgfd">
              <li><a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site"
                target="_blank">Terms and conditions</a></li>
              <li><a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site"
                target="_blank">Game Addiction</a></li>
              <li><a href="http://wa.me//919284451075?text=Hi! I need ID to play on your Site"
                target="_blank">Privacy Policy</a></li>
            </ul>
          </div>
        </div>
      </footer>
    </>
  )
}
